[rpc]
endpoint = "https://rpc.testnet.miden.io"
timeout_ms = 10000

[solver]
account_id = "0x271347ea6b58cd103873d099262800"
keystore_path = "./keystore"
store_path = "./store.sqlite3"

[[pairs]]
name = "USDT-ETH"
asset_x_faucet_id = "0x1c475ac0305af32063854700a7f0db"
asset_y_faucet_id = "0x61f706d05629a420231af0ab576d80"

[engine]
pulse_interval_ms = 5000
fetch_interval_ms = 3000

[dashboard]
enabled = true
ws_port = 3001
