-- Initial application database for a fresh solver deployment. The Miden client
-- stores remain separate SQLite databases.

CREATE TABLE sync_state (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    last_fetched_block BIGINT NOT NULL DEFAULT 0 CHECK (last_fetched_block >= 0)
);
INSERT INTO sync_state (id, last_fetched_block) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

-- One row per PSWAP order. `raw_data` is the serialized note and the only
-- source of its terms; a remainder inherits its parent's `priority_seq`.
CREATE TABLE orders (
    note_id BYTEA PRIMARY KEY,
    raw_data BYTEA NOT NULL,
    arrival_unix BIGINT NOT NULL CHECK (arrival_unix >= 0),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'settling', 'executed', 'onchain_nullified')),
    priority_seq BIGINT GENERATED BY DEFAULT AS IDENTITY CHECK (priority_seq > 0)
);
CREATE INDEX orders_active_priority_idx ON orders (priority_seq)
WHERE status = 'active';

-- Unresolved settlements only: a row is deleted once its transaction is
-- confirmed or definitely never commits.
CREATE TABLE settlement_attempts (
    tx_id BYTEA PRIMARY KEY,
    tx_result BYTEA NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('prepared', 'uncertain', 'rejected'))
);

CREATE TABLE settlement_inputs (
    tx_id BYTEA NOT NULL REFERENCES settlement_attempts(tx_id) ON DELETE CASCADE,
    parent_note_id BYTEA NOT NULL REFERENCES orders(note_id) ON DELETE RESTRICT,
    child_note_id BYTEA,
    child_note_data BYTEA,
    PRIMARY KEY (tx_id, parent_note_id),
    CHECK ((child_note_id IS NULL) = (child_note_data IS NULL))
);
CREATE INDEX settlement_inputs_parent_idx ON settlement_inputs (parent_note_id);
CREATE UNIQUE INDEX settlement_inputs_child_unique_idx ON settlement_inputs (child_note_id)
WHERE child_note_id IS NOT NULL;

CREATE TABLE registered_tokens (
    token_id BYTEA PRIMARY KEY,
    external_symbol TEXT,
    decimals INTEGER,
    ticker TEXT
);
