-- Initial application database for a fresh solver deployment. The Miden client
-- stores remain separate SQLite databases.

CREATE TABLE sync_state (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    last_fetched_block BIGINT NOT NULL DEFAULT 0 CHECK (last_fetched_block >= 0)
);
INSERT INTO sync_state (id, last_fetched_block) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE notes (
    note_id BYTEA PRIMARY KEY,
    account_id BYTEA NOT NULL,
    raw_data BYTEA NOT NULL
);

CREATE TABLE orders (
    note_id BYTEA PRIMARY KEY REFERENCES notes(note_id) ON DELETE RESTRICT,
    account_id BYTEA NOT NULL,
    requested_asset BYTEA NOT NULL,
    requested_amount BIGINT NOT NULL,
    offered_asset BYTEA NOT NULL,
    offered_amount BIGINT NOT NULL,
    arrival_unix BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'settling', 'executed', 'onchain_nullified')),
    priority_seq BIGINT GENERATED BY DEFAULT AS IDENTITY CHECK (priority_seq > 0)
);
CREATE INDEX orders_active_priority_idx ON orders (priority_seq)
WHERE status = 'active';

CREATE TABLE settlement_attempts (
    tx_id BYTEA PRIMARY KEY,
    tx_result BYTEA NOT NULL,
    status TEXT NOT NULL
        CHECK (status IN ('prepared', 'submitted', 'uncertain', 'rejected', 'confirmed')),
    created_at_unix BIGINT NOT NULL
);
CREATE INDEX settlement_attempts_unresolved_idx ON settlement_attempts (status)
WHERE status <> 'confirmed';

CREATE TABLE settlement_inputs (
    tx_id BYTEA NOT NULL REFERENCES settlement_attempts(tx_id) ON DELETE CASCADE,
    parent_note_id BYTEA NOT NULL REFERENCES orders(note_id) ON DELETE RESTRICT,
    payback_note_id BYTEA NOT NULL,
    child_note_id BYTEA,
    child_note_data BYTEA,
    PRIMARY KEY (tx_id, parent_note_id),
    CHECK ((child_note_id IS NULL) = (child_note_data IS NULL))
);
CREATE INDEX settlement_inputs_parent_idx ON settlement_inputs (parent_note_id);
CREATE UNIQUE INDEX settlement_inputs_child_unique_idx ON settlement_inputs (child_note_id)
WHERE child_note_id IS NOT NULL;

CREATE TABLE registered_tokens (
    token_id BYTEA PRIMARY KEY,
    created_at_unix BIGINT NOT NULL,
    external_symbol TEXT,
    decimals INTEGER,
    ticker TEXT
);
