//! Persisted provisioning artifacts: the on-chain ids the harness creates, plus
//! generation of a ready-to-run `solver.toml` pointed at devnet.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Directory (relative to the solver repo root) holding all e2e state:
/// stores, keystores, the artifacts file, and the generated solver config.
pub const E2E_DIR: &str = "e2e";

/// Path to the JSON artifacts file written by `provision`.
pub fn artifacts_path() -> String {
    format!("{E2E_DIR}/provisioned.json")
}

/// Path to the generated solver config written by `provision`.
pub fn solver_config_path() -> String {
    format!("{E2E_DIR}/solver.devnet.toml")
}

/// The solver's executor store / keystore (the solver account lives here, so the
/// solver runtime's executor client finds it). Shared between `provision` and
/// `run`.
pub fn solver_executor_store() -> String {
    format!("{E2E_DIR}/solver_executor.sqlite3")
}
pub fn solver_ingest_store() -> String {
    format!("{E2E_DIR}/solver_ingest.sqlite3")
}
pub fn solver_app_db() -> String {
    format!("{E2E_DIR}/solver_app.sqlite3")
}
pub fn solver_keystore() -> String {
    format!("{E2E_DIR}/solver_keystore")
}

/// The "operator" context store/keystore: owns the faucets and the user wallets
/// that mint tokens and create PSWAP/P2ID notes.
pub fn operator_store() -> String {
    format!("{E2E_DIR}/operator.sqlite3")
}
pub fn operator_keystore() -> String {
    format!("{E2E_DIR}/operator_keystore")
}

/// A single tradable token: its faucet id + decimals + an external price symbol
/// (only meaningful for the production HttpPriceClient; `run` injects fixed
/// prices and ignores it).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenInfo {
    pub faucet_id: String,
    pub symbol: String,
    pub decimals: u8,
    /// Price symbol the solver maps this token to (e.g. "tether").
    pub external_symbol: String,
}

/// Everything `provision` produces. Consumed by `fund`, `load`, and `run`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Artifacts {
    pub rpc_endpoint: String,
    pub solver_account_id: String,
    pub token_a: TokenInfo,
    pub token_b: TokenInfo,
    /// Solver keystore + store paths (so `run` configures the runtime identically).
    pub solver_keystore_path: String,
    pub solver_executor_store_path: String,
    pub solver_ingest_store_path: String,
    pub solver_app_db_path: String,
    /// Operator context (faucets + user wallets).
    pub operator_store_path: String,
    pub operator_keystore_path: String,
}

impl Artifacts {
    pub fn save(&self, path: &str) -> Result<()> {
        let json = serde_json::to_string_pretty(self).context("serialize artifacts")?;
        std::fs::write(path, json).with_context(|| format!("write artifacts to {path}"))?;
        Ok(())
    }

    pub fn load(path: &str) -> Result<Self> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("read artifacts from {path} (run `e2e provision` first?)"))?;
        serde_json::from_str(&raw).context("parse artifacts")
    }

    /// Render a `solver.toml` that runs the solver against devnet with the
    /// provisioned account + the TOK_A/TOK_B pair.
    pub fn render_solver_config(&self) -> String {
        format!(
            r#"# Generated by `e2e provision`. Runs the solver against devnet with the
# provisioned solver account + the TOK_A/TOK_B faucet pair.
[rpc]
endpoint = "{rpc}"
timeout_ms = 10000

[solver]
account_id = "{solver}"
keystore_path = "{keystore}"
app_db_path = "{app_db}"
executor_store_path = "{exec_store}"
ingest_store_path = "{ingest_store}"
read_pool_size = 4

[[pairs]]
name = "{sym_a}-{sym_b}"
asset_x_faucet_id = "{faucet_a}"
asset_x_external_symbol = "{ext_a}"
asset_y_faucet_id = "{faucet_b}"
asset_y_external_symbol = "{ext_b}"

[engine]
pulse_interval_ms = 5000
fetch_interval_ms = 3000
price_interval_ms = 5000
triangular_enabled = true
admin_port = 3001
obs_port = 9090
# Devnet test tokens aren't on public CoinGecko, so point the price client at
# the local mock service: run `cargo run -p mock-price` in another terminal first.
price_api_base_url = "http://127.0.0.1:8089/api/v3/simple/price"
"#,
            rpc = self.rpc_endpoint,
            solver = self.solver_account_id,
            keystore = self.solver_keystore_path,
            app_db = self.solver_app_db_path,
            exec_store = self.solver_executor_store_path,
            ingest_store = self.solver_ingest_store_path,
            sym_a = self.token_a.symbol,
            sym_b = self.token_b.symbol,
            faucet_a = self.token_a.faucet_id,
            ext_a = self.token_a.external_symbol,
            faucet_b = self.token_b.faucet_id,
            ext_b = self.token_b.external_symbol,
        )
    }

    pub fn write_solver_config(&self, path: &str) -> Result<()> {
        std::fs::write(path, self.render_solver_config())
            .with_context(|| format!("write solver config to {path}"))?;
        Ok(())
    }
}

/// Ensure the `e2e/` state directory exists.
pub fn ensure_dir() -> Result<()> {
    std::fs::create_dir_all(E2E_DIR).with_context(|| format!("create {E2E_DIR}/"))?;
    Ok(())
}
