//! Persisted provisioning artifacts: the on-chain ids the harness creates, plus
//! generation of a ready-to-run `solver.toml` pointed at devnet.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Directory (relative to the solver repo root) holding all e2e state:
/// stores, keystores, the artifacts file, and the generated solver config.
pub const E2E_DIR: &str = "e2e";

/// Path to the JSON artifacts file written by `provision`.
pub fn artifacts_path() -> String {
    format!("{E2E_DIR}/provisioned.json")
}

/// Path to the generated solver config written by `provision`.
pub fn solver_config_path() -> String {
    format!("{E2E_DIR}/solver.devnet.toml")
}

/// The solver's executor store / keystore (the solver account lives here, so the
/// solver runtime's executor client finds it). Shared between `provision` and
/// `run`.
pub fn solver_executor_store() -> String {
    format!("{E2E_DIR}/solver_executor.sqlite3")
}
pub fn solver_ingest_store() -> String {
    format!("{E2E_DIR}/solver_ingest.sqlite3")
}
pub fn solver_keystore() -> String {
    format!("{E2E_DIR}/solver_keystore")
}

/// The "operator" context store/keystore: owns the faucets and the user wallets
/// that mint tokens and create PSWAP/P2ID notes.
pub fn operator_store() -> String {
    format!("{E2E_DIR}/operator.sqlite3")
}
pub fn operator_keystore() -> String {
    format!("{E2E_DIR}/operator_keystore")
}

/// A single tradable token: its faucet id + decimals + the Binance asset it is
/// priced as.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenInfo {
    pub faucet_id: String,
    pub symbol: String,
    pub decimals: u8,
    /// Binance asset code the solver prices this token as (e.g. "USDT").
    pub binance_asset: String,
}

/// Everything `provision` produces. Consumed by `fund`, `load`, and `run`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Artifacts {
    pub rpc_endpoint: String,
    pub solver_account_id: String,
    pub token_a: TokenInfo,
    pub token_b: TokenInfo,
    /// Binance symbol of the direct market between the two assets.
    pub binance_symbol: String,
    /// Solver keystore + store paths (so `run` configures the runtime identically).
    pub solver_keystore_path: String,
    pub solver_executor_store_path: String,
    pub solver_ingest_store_path: String,
    /// Operator context (faucets + user wallets).
    pub operator_store_path: String,
    pub operator_keystore_path: String,
}

impl Artifacts {
    pub fn save(&self, path: &str) -> Result<()> {
        let json = serde_json::to_string_pretty(self).context("serialize artifacts")?;
        std::fs::write(path, json).with_context(|| format!("write artifacts to {path}"))?;
        Ok(())
    }

    pub fn load(path: &str) -> Result<Self> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("read artifacts from {path} (run `e2e provision` first?)"))?;
        serde_json::from_str(&raw).context("parse artifacts")
    }

    /// Render a `solver.toml` that runs the solver against devnet with the
    /// provisioned account + the TOK_A/TOK_B pair.
    pub fn render_solver_config(&self) -> String {
        format!(
            r#"# Generated by `e2e provision`. Runs the solver against devnet with the
# provisioned solver account + the TOK_A/TOK_B faucet pair.
[rpc]
endpoint = "{rpc}"
timeout_ms = 10000

[solver]
account_id = "{solver}"
keystore_path = "{keystore}"
executor_store_path = "{exec_store}"
ingest_store_path = "{ingest_store}"
read_pool_size = 4

[[pairs]]
name = "{sym_a}-{sym_b}"
asset_x_faucet_id = "{faucet_a}"
asset_x_binance_asset = "{asset_a}"
asset_y_faucet_id = "{faucet_b}"
asset_y_binance_asset = "{asset_b}"
binance_symbol = "{binance_symbol}"

[engine]
pulse_interval_ms = 5000
fetch_interval_ms = 3000
clearing_fee_ppm = 0
admin_port = 3001
obs_port = 9090

# Devnet test tokens have no Binance market of their own: they are priced as
# {asset_b} and {asset_a} on Binance's public Spot Testnet (no API key, nothing
# to run locally). Testnet markets update only when their book changes, hence
# the long quote TTL. For fixed 1:1 prices offline instead, run
#   cargo run -p mock-binance -- --market {binance_symbol}={asset_b}/{asset_a}:1/1
# and use ws://127.0.0.1:8089 and http://127.0.0.1:8089 below
# (`e2e run --mock-prices` starts its own mock and overrides these endpoints).
[binance]
stream_endpoints = ["wss://stream.testnet.binance.vision", "wss://stream.testnet.binance.vision"]
rest_endpoint = "https://testnet.binance.vision"
quote_ttl_ms = 30000
max_spread_bps = 100
"#,
            rpc = self.rpc_endpoint,
            solver = self.solver_account_id,
            keystore = self.solver_keystore_path,
            exec_store = self.solver_executor_store_path,
            ingest_store = self.solver_ingest_store_path,
            sym_a = self.token_a.symbol,
            sym_b = self.token_b.symbol,
            faucet_a = self.token_a.faucet_id,
            asset_a = self.token_a.binance_asset,
            faucet_b = self.token_b.faucet_id,
            asset_b = self.token_b.binance_asset,
            binance_symbol = self.binance_symbol,
        )
    }

    pub fn write_solver_config(&self, path: &str) -> Result<()> {
        std::fs::write(path, self.render_solver_config())
            .with_context(|| format!("write solver config to {path}"))?;
        Ok(())
    }
}

/// Ensure the `e2e/` state directory exists.
pub fn ensure_dir() -> Result<()> {
    std::fs::create_dir_all(E2E_DIR).with_context(|| format!("create {E2E_DIR}/"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated config loads as `run` and `solver-bin` load it, and
    /// prices the pair on the Spot Testnet.
    #[test]
    fn generated_solver_config_is_valid() {
        let token = |faucet_id: &str, symbol: &str, binance_asset: &str| TokenInfo {
            faucet_id: faucet_id.to_string(),
            symbol: symbol.to_string(),
            decimals: 8,
            binance_asset: binance_asset.to_string(),
        };
        let art = Artifacts {
            rpc_endpoint: "https://rpc.devnet.miden.io".to_string(),
            solver_account_id: "0x9f0c6ec13c4ed2b1076a2990a9fc29".to_string(),
            token_a: token("0x9f0c6ec13c4ed2b1076a2990a9fc29", "MTA", "USDT"),
            token_b: token("0x3ae73d7f166f723132e3acbba75e75", "MTB", "USDC"),
            binance_symbol: "USDCUSDT".to_string(),
            solver_keystore_path: solver_keystore(),
            solver_executor_store_path: solver_executor_store(),
            solver_ingest_store_path: solver_ingest_store(),
            operator_store_path: operator_store(),
            operator_keystore_path: operator_keystore(),
        };
        let path = std::env::temp_dir().join(format!("e2e-solver-{}.toml", std::process::id()));
        let path = path.to_str().unwrap();
        art.write_solver_config(path).unwrap();
        let config = solver::config::SolverConfig::load(path);
        std::fs::remove_file(path).unwrap();
        let config = config.unwrap();
        assert_eq!(
            config.binance.rest_endpoint,
            "https://testnet.binance.vision"
        );
        assert_eq!(
            config.pairs[0].binance_symbol.as_ref().unwrap().to_string(),
            "USDCUSDT"
        );
    }
}
