[package]
name = "consume-script"
version = "0.1.0"
edition = "2021"

[dependencies]
miden-protocol = { git = "https://github.com/0xMiden/protocol", branch = "next", default-features = false, features = ["testing"] }
miden-standards = { git = "https://github.com/0xMiden/protocol", branch = "next" }
miden-crypto = "0.23"
miden-core = "0.22"

[dev-dependencies]
miden-testing = { git = "https://github.com/0xMiden/protocol", branch = "next" }
solver = { path = "../solver", features = ["testing"] }
tokio = { version = "1", features = ["rt", "macros"] }
anyhow = "1.0"
